### ISSUE TITLE
Feature Request: Add "Gathering Swarm always on" and "World Sense always on" as a "Full Explorer's toolkit"

### ISSUE THREAD

**Issue by NebuPookins** [flibber-hk/HollowKnight.CompassAlwaysOn#1]
Not sure if this should be part of this mod, or as a new mod, but I'd greatly appreciate these features either way.

**Comment by flibber-hk** [comment]
I just did the GatheringSwarmAlwaysOn thing (new mod, will appear on Scarab probably soon). 

For WorldSenseAlwaysOn, I do not think I will make that a separate mod - there are various mods (like PlayerDataManager and MoreSaves) which can mimic the relevant functionality sufficiently well that I do not want to make a separate mod.

**Comment by NebuPookins** [comment]
Thank you very much. I did not realize PlayerDataManager had a menu option to enable showing progression. It wasn't clear from the README that it could do this, but I tried installing it anyway and it worked.
